### ISSUE TITLE
Abandon webapp-meta

### ISSUE THREAD

**Issue by oliveradria** [symfony/recommended-meta#1]
Hi!
I just found this package in one of the projects I started maintaining / cleaning up. I assume this repo was created, then re-created as `webapp-pack`, so I can safely remove this one.

It still has ca. 1k installs per day (and has 3 dependents). Perhaps it might be useful to abandon this repo to reduce confusion.

What do you think?

Cheers

**Comment by fabpot** [comment]
Will do, thank you.
